# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 604a9e8a19c7919053770f657171ccc92050aacd7295bd40abab0eee0b6614d79517c28eb08f687c58d99d60e110fe10c93b0c28810dd4bcdc02058f671332b1

test:
  secret_key_base: 1dddb52598e3552d300aa49ab6e38e462a4f84b12212c2564eae4f258f7c90d4dacde0d794c04402aef71792a992dcf82846f190eda9ae93bd305976aecc50a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
